name: Build & Test - Clang-10

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.7
      with:
        cmake-version: '3.19.x'

    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Install Clang-10
      run: |
        sudo apt-get update
        sudo apt install clang-10
    - name: Configure & Build
      run: |
        cmake . -Bbuild_clang -DCMAKE_C_COMPILER=$(which clang-10) -DCMAKE_CXX_COMPILER=$(which clang++-10) -DSIMPLE_LOG_BUILD_EXAMPLES=ON
        cmake --build build_clang
    - name: Test
      run:
        cmake --build build_clang --target test
