name: Build & Test - MSVC

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.7
      with:
        cmake-version: '3.19.x'

    - name: Configure & Build
      run: |
        cmake . -Bbuild_msvc -DSIMPLE_LOG_BUILD_EXAMPLES=ON
        cmake --build build_msvc
    - name: Test
      run:
        cmake --build build_msvc --target RUN_TESTS
